name = "Creativity Modpack"
author = "Stevenbf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32204f20db5c661fcc7ecb23d7e6a0aecc336e7f1e9b815a293a2ec6cbc2c32e"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
