name = "Creativity Modpack"
author = "Stevenbf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3792acce6234a75281a69e7ecb8c68f84dc8a964a651b92565766f23162af606"

[versions]
forge = "50.2.0"
minecraft = "1.20.6"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2", "1.20.3", "1.20.4", "1.20.5"]
